# http://module-build.sourceforge.net/META-spec.html
#
name:         WWW-iloxx-Detail
version:      0.1
version_from: Detail.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
